language: php

sudo: required

services:
    - docker

before_script:
    - docker network create --driver=bridge event-broker
    - docker run -d --name event-broker-rabbitmq --network event-broker rabbitmq:3-management
    - docker build -t event-broker-amqp .
    - docker run -it -d --name event-broker-amqp --network event-broker -e "RABBITMQ_HOST=event-broker-rabbitmq" event-broker-amqp
    - docker exec event-broker-rabbitmq sh -c "rabbitmqctl await_startup"

script:
    - docker cp . event-broker-amqp:/code
    - docker exec event-broker-amqp  composer update --prefer-stable
    - docker exec event-broker-amqp  bin/phpcs --config-set show_warnings 0
    - docker exec event-broker-amqp  bin/phpcs --standard=vendor/escapestudios/symfony2-coding-standard/Symfony/ src/
    - docker exec event-broker-amqp  bin/phpcs --standard=tests/phpcs-ruleset.xml tests/

    # Test on stable vendors
    - docker exec event-broker-amqp  bin/phpunit

    # Test on lowest vendors
    - docker exec event-broker-amqp  composer update --prefer-lowest
    - docker exec event-broker-amqp  bin/phpunit

after_script:
    - docker kill $(docker ps -q)
    - docker rm $(docker ps -a -q)
