name: Testing

on:
    push:
    pull_request:

jobs:
    code-style:
        name: Check code style
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: "none"
                    extensions: "json,amqp"
                    ini-values: "memory_limit=-1"
                    php-version: "7.4"
                    tools: "composer"

            -   name: Install vendors
                run: composer install --prefer-dist

            -   name: Check style on sources
                run: bin/phpcs --standard=src/phpcs-ruleset.xml src/

            -   name: Check style on tests
                run: bin/phpcs --standard=tests/phpcs-ruleset.xml tests/

    php-stan:
        name: Run PHP-Stan
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: "none"
                    extensions: "json,amqp"
                    ini-values: "memory_limit=-1"
                    php-version: "7.4"
                    tools: "composer"

            -   name: Install vendors
                run: composer install --prefer-dist

            -   name: Run php stan
                run: bin/phpstan

    tests:
        name: Run tests
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php: [ '7.4', '8.0', '8.1', '8.2' ]

        services:
            rabbitmq:
                image: rabbitmq:3-management
                ports:
                    - 5672:5672
                    - 15672:15672
                options: --health-cmd "rabbitmqctl await_startup" --health-interval 10s --health-timeout 5s --health-retries 5

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: "none"
                    extensions: "json,amqp"
                    ini-values: "memory_limit=-1"
                    php-version: "${{ matrix.php }}"
                    tools: "composer"

            -   name: Install vendors (stable)
                run: composer install --prefer-dist

            -   name: Run tests
                run: bin/phpunit
                env:
                    RABBITMQ_HOST: localhost

            -   name: Install vendors (lowest)
                run: composer update --prefer-lowest

            -   name: Run tests
                run: bin/phpunit
                env:
                    RABBITMQ_HOST: localhost
