name: Testing

on:
    push:
    pull_request:

jobs:
    tests:
        name: Run tests
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php: [ '7.1', '7.2', '7.4' ]

        services:
            rabbitmq:
                image: rabbitmq:3.8.3
                ports:
                    - 5672:5672

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: "none"
                    extensions: "json,amqp"
                    ini-values: "memory_limit=-1"
                    php-version: "${{ matrix.php }}"
                    tools: "composer"

            -   name: Run tests on stable packages
                run: |
                    composer install --prefer-dist
                    ./bin/phpunit
                env:
                    RABBITMQ_HOST: localhost

            -   name: Run tests on lowest versioin of packages
                run: |
                    composer update --prefer-lowest
                    ./bin/phpunit
                env:
                    RABBITMQ_HOST: localhost
